export const CHECK_LOGIN_TOKEN_ACTION_INIT =  'CHECK_LOGIN_TOKEN_ACTION_INIT'
export const CHECK_LOGIN_TOKEN_ACTION_ERROR =  'CHECK_LOGIN_TOKEN_ACTION_ERROR'
export const CHECK_LOGIN_TOKEN_ACTION_SUCCESS =  'CHECK_LOGIN_TOKEN_ACTION_SUCCESS'
export const CHECK_LOGIN_TOKEN_ACTION_RESET =  'CHECK_LOGIN_TOKEN_ACTION_RESET'

export const CHECK_LOGIN_ACTION_INIT =  'CHECK_LOGIN_ACTION_INIT'
export const CHECK_LOGIN_ACTION_ERROR =  'CHECK_LOGIN_ACTION_ERROR'
export const CHECK_LOGIN_ACTION_SUCCESS =  'CHECK_LOGIN_ACTION_SUCCESS'
export const CHECK_LOGIN_ACTION_RESET =  'CHECK_LOGIN_ACTION_RESET'
