export const GET_CHARACTERS_INIT = 'GET_CHARACTERS_INIT';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const SET_CURRENT_CHARACTER_INIT = 'SET_CURRENT_CHARACTER_INIT';
export const SET_CURRENT_CHARACTER_SUCCESS = 'SET_CURRENT_CHARACTER_SUCCESS';
export const SET_CURRENT_CHARACTER_ERROR = 'SET_CURRENT_CHARACTER_ERROR';

export const GET_CURRENT_CHARACTER_INIT = 'GET_CURRENT_CHARACTER_INIT';
export const GET_CURRENT_CHARACTER_SUCCESS = 'GET_CURRENT_CHARACTER_SUCCESS';
export const GET_CURRENT_CHARACTER_ERROR = 'GET_CURRENT_CHARACTER_ERROR';