export const GET_BY_ID_INIT =  'GET_BY_ID_INIT'
export const GET_BY_ID_ERROR =  'GET_BY_ID_ERROR'
export const GET_BY_ID_SUCCESS =  'GET_BY_ID_SUCCESS'
export const GET_BY_ID_RESET =  'GET_BY_ID_RESET'

export const ADD_COMMENT_INIT =  'ADD_COMMENT_INIT'
export const ADD_COMMENT_ERROR =  'ADD_COMMENT_ERROR'
export const ADD_COMMENT_SUCCESS =  'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_RESET =  'ADD_COMMENT_RESET'

export const DELETE_COMMENT_INIT =  'DELETE_COMMENT_INIT'
export const DELETE_COMMENT_ERROR =  'DELETE_COMMENT_ERROR'
export const DELETE_COMMENT_SUCCESS =  'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_RESET =  'DELETE_COMMENT_RESET'

export const MODIFY_COMMENT_INIT =  'MODIFY_COMMENT_INIT'
export const MODIFY_COMMENT_ERROR =  'MODIFY_COMMENT_ERROR'
export const MODIFY_COMMENT_SUCCESS =  'MODIFY_COMMENT_SUCCESS'
export const MODIFY_COMMENT_RESET =  'MODIFY_COMMENT_RESET'
